package com.ranosys.theexecutive.utils

/**
 * Created by Mohammad Sunny on 22/2/18.
 */
object Constants {
        val PREF_NAME = "data_pref"
        const val ADMIN_TOKEN = "cigid62rumgjietso83lrlk16c5ki7bp"
        val pref_name = "data_pref"
        val STORE_ID_KEY = "store_id"
        val ACCESS_TOKEN_KEY = "access_token"
        val USER_ACCESS_TOKEN_KEY = "user_access_token"
        val USER_CART_ID_KEY = "user_cart_id_key"
        val GUEST_CART_ID_KEY = "guest_cart_id_key"
        val DEFAULT_STORE_CODE = "en"
        val SELECTED_STORE_CODE_KEY = "selected_store_code"
        val SELECTED_STORE_ID_KEY = "selected_store_id"
        val SELECTED_WEBSITE_ID_KEY = "selected_website_id"
        val ANDROID_DEVICE_ID_KEY = "device_id"
        val MESSAGE = "message"
        val ERROR = "Error"
        val MAINTENENCE_OFF = "0"
        val MAINTENENCE_ON = "1"
        val CONFIG_FILE_NAME = "config"
        val FORGOT_PASSWORD_REQUEST_PARAM_TEMPLATE = "email_reset"
        val ALL: String = "all"
        val TYPE_FACEBOOK: String = "facebook"
        val TYPE_GMAIL: String = "google"
        val UNKNOWN_ERROR: String = "Something went wrong"
        val PRODUCT_MEDIA_URL: String = "product_media_url"
        val CATEGORY_MEDIA_URL: String = "category_media_url"
        val CATEGORY_ID: String = "categoryId"
        val LOGIN_REQUIRED_PROMPT: String = "login_required_prompt"
        val CATEGORY_NAME: String = "categoryName"
        val VOUCHER_AMT: String = "voucher_amount"
        val SUBS_MESSAGE: String = "subscription_message"
        val PROMOTION_MESSAGE: String = "home_promotion_message"
        val DEFAULT_GROUP_ID: Int = 1
        val SOCIAL_LOGIN_CONFIRMATION: String = "social"
        val MINIMUM_AGE: Int = 13
        val FROM_SOCIAL_LOGIN: String = "from_social"
        val FROM_SOCIAL_LOGIN_FIRST_NAME: String? = "from_social_first_name"
        val FROM_SOCIAL_LOGIN_LAST_NAME: String? = "from_social_last_name"
        val FROM_SOCIAL_LOGIN_EMAIL: String? = "from_social_email"
        val DD_MM_YY_DATE_FORMAT: String = "dd/MM/yyyy"
        val YY_MM__DD_DATE_FORMAT: String = "yyyy-MM-dd"
        val COUNTRY_LABEL: String = "Country"
        val STATE_LABEL: String = "State/ Province"
        val CITY_LABEL: String = "City"
        val USER_EMAIL: String = "user_email"
        val PRODUCT_LIST_RESPONSE: String = "product_list_response"
        val LIST_PAGE_ITEM_COUNT: Int = 10
        val FILTER_PRICE_LABEL: String = "Price"
        val FILTER_PRICE_KEY: String = "price"
        val SORT_OPTION_LABEL: String = "product_list_order"
        val SORT_OPTION_DIR: String = "product_list_dir"
        val FILTER_CONFIGURABLE_LABEL: String = "configurable"
        val FILTER_SPECIAL_PRICE_LABEL: String = "special_price"
        val NEW_FROM_DATE_LABEL: String = "news_from_date"
        val NEW_TO_DATE_LABEL: String = "news_to_date"
        val REQUEST_PAGE_LABEL: String = "p"
        val REQUEST_PAGE_LIMIT_LABEL: String = "product_list_limit"
        val REQUEST_SEARCH_LABEL: String = "q"
        val REQUEST_ID_LABEL: String = "id"
        val LOW_TO_HIGH: String = " (Low to High)"
        val HIGH_TO_LOW: String = " (High to Low)"
        val DESC: String = "desc"
        val ASC: String = "asc"
        val NEW_TAG: String = "New"
        val AIMATION_DURATION: Long = 300
        val IDR: String = "IDR "
        val PROMOTION_TYPE_CATEGORY: String = "Category"
        val PROMOTION_TYPE_PRODUCT: String = "Product"
        val PROMOTION_TYPE_CMS_PAGE: String = "CMS"
        val SEARCH_FROM_HOME_QUERY: String? = "search_from_home_query"
        val UNIVERSAL_CAT_ID: Int = 0
        val URL_KEY: String = "url_key"
        val URL_SUFFIX: String = ".html"
        val SORT_TYPE_CATALOG: String = "catalog"
        val SORT_TYPE_SEARCH: String = "search"
        val LIST_TAG_KEY: String = "tag_text"

}