package com.delamibrands.theexecutive.utils

/**
 * Created by Mohammad Sunny on 22/2/18.
 */
object Constants {
    const val ACCESS_TOKEN_KEY = "access_token"
    const val USER_ACCESS_TOKEN_KEY = "user_access_token"
    const val USER_CART_ID_KEY = "user_cart_id_key"
    const val GUEST_CART_ID_KEY = "guest_cart_id_key"
    const val DEFAULT_STORE_CODE = "en"
    const val DEFAULT_STORE_LANGUAGE = "English"
    const val SELECTED_STORE_CODE_KEY = "selected_store_code"
    const val SELECTED_STORE_ID_KEY = "selected_store_id"
    const val SELECTED_WEBSITE_ID_KEY = "selected_website_id"
    const val ANDROID_DEVICE_ID_KEY = "device_id"
    const val HEIGHT = "height"
    const val ORIENTATION = "orientation"
    const val WIDTH = "width"
    const val OS_TYPE = "android"
    const val MESSAGE = "message"
    const val ERROR = "Error"
    const val MAINTENENCE_OFF = "0"
    const val CONFIG_FILE_NAME = "config"
    const val CONFIG_FILE_PRODUCTION = "proconfig"
    const val FORGOT_PASSWORD_REQUEST_PARAM_TEMPLATE = "email_reset"
    const val ALL: String = "all"
    const val TYPE_FACEBOOK: String = "facebook"
    const val TYPE_GMAIL: String = "google"
    const val CATEGORY_ID: String = "categoryId"
    const val LOGIN_REQUIRED_PROMPT: String = "login_required_prompt"
    const val CATEGORY_NAME: String = "categoryName"
    const val DEFAULT_GROUP_ID: Int = 1
    const val SOCIAL_LOGIN_CONFIRMATION: String = "social"
    const val MINIMUM_AGE: Int = 13
    const val FROM_SOCIAL_LOGIN: String = "from_social"
    const val FROM_SOCIAL_LOGIN_FIRST_NAME: String = "from_social_first_name"
    const val FROM_SOCIAL_LOGIN_LAST_NAME: String = "from_social_last_name"
    const val FROM_SOCIAL_LOGIN_EMAIL: String = "from_social_email"
    const val DD_MM_YY_DATE_FORMAT: String = "dd/MM/yyyy"
    const val YY_MM__DD_DATE_FORMAT: String = "yyyy-MM-dd"
    const val CITY_LABEL: String = "City"
    const val USER_EMAIL: String = "user_email"
    const val LIST_PAGE_ITEM_COUNT: Int = 20
    const val FILTER_PRICE_LABEL: String = "Price"
    const val FILTER_PRICE_KEY: String = "price"
    const val SORT_OPTION_LABEL: String = "product_list_order"
    const val SORT_OPTION_DIR: String = "product_list_dir"
    const val CONFIGURABLE: String = "configurable"
    const val SIMPLE: String = "simple"
    const val RELATED: String = "related"
    const val FILTER_SPECIAL_PRICE_LABEL: String = "special_price"
    const val NEW_FROM_DATE_LABEL: String = "news_from_date"
    const val NEW_TO_DATE_LABEL: String = "news_to_date"
    const val SHORT_DESCRIPTION: String = "short_description"
    const val COLOR: String = "color"
    const val COLOR_: String = "Color"
    const val IN_COLOR: String = "Warna"
    const val SIZE: String = "size"
    const val SIZE_: String = "Size"
    const val IN_SIZE: String = "Ukuran"
    const val REQUEST_PAGE_LABEL: String = "p"
    const val REQUEST_PAGE_LIMIT_LABEL: String = "product_list_limit"
    const val REQUEST_SEARCH_LABEL: String = "q"
    const val REQUEST_ID_LABEL: String = "id"
    const val LOW_TO_HIGH: String = " (Low to High)"
    const val HIGH_TO_LOW: String = " (High to Low)"
    const val DESC: String = "desc"
    const val ASC: String = "asc"
    const val NEW_TAG: String = "New"
    const val TYPE_CATEGORY: String = "Category"
    const val TYPE_PRODUCT: String = "Product"
    const val TYPE_CMS_PAGE: String = "CMS"
    const val TYPE_ORDER: String = "Order"
    const val SEARCH_FROM_HOME_QUERY: String = "search_from_home_query"
    const val SEARCH_QUERY: String = "search_query"
    const val UNIVERSAL_CAT_ID: Int = 0
    const val URL_KEY: String = "url_key"
    const val URL_SUFFIX: String = ".html"
    const val SORT_TYPE_CATALOG: String = "catalog"
    const val SORT_TYPE_SEARCH: String = "search"
    const val SPLASH_TIMEOUT: Long = 3000
    const val PROMOTION_TOAST_TIMEOUT: Long = 3000
    const val CLICK_TIMEOUT: Long = 3000
    const val ERROR_CODE_404: Int = 404
    const val ERROR_CODE_401: Int = 401
    const val ERROR_CODE_400: Int = 400
    const val ZENDESK_CHAT: String = "4gHlsXEXVL3ZjRJ6jA5W66wwYYcJPdef"
    const val ZERO: String = "0"
    const val FIRST_NAME: String = "first_name"
    const val LAST_NAME: String = "last_name"
    const val PRODUCT_SKU: String = "productSku"
    const val ORDER_ID: String = "order_id"
    const val PAYMENT_METHOD_BANK_TRANSFER_KEY: String = "banktransfer"
    const val PAYMENT_METHOD_COD_KEY: String = "cashondelivery"
    const val GRAND_TOTAL_KEY: String = "grand_total"
    const val IDR: String = "IDR"
    const val NOTIFICATION_CHANNEL_ID = "4655"
    var notificationCounter = 0
    const val KEY_REDIRECTION_TYPE = "type"
    const val KEY_REDIRECTION_VALUE = "typeId"
    const val KEY_APP_IN_BACKGROUND = "appInBackground"
    const val KEY_IMAGE = "image_url"
    const val KEY_TITLE = "title"
    const val KEY_BODY = "body"
    const val KEY_REDIRECTION_TITLE = "redirect_title"
    const val KEY_NOTIFICATION_TITLE = "gcm.notification.title"
    const val KEY_NOTIFICATION_ALERT = "notification_alert"
    const val KEY_NOTIFICATION_ID = "notification_id"
    const val FROM_NOTIFICATION = "from_notification"
    const val KEY_NOTIFICATION_MESSAGE = "gcm.notification.body"
    const val NOTIFICATION_TYPE_CMS = "cms"
    const val NOTIFICATION_TYPE_PRODUCT_DETAIL = "Product"
    const val NOTIFICATION_TYPE_CATALOG = "Category"
    const val NOTIFICATION_TYPE_ORDER_LIST = "Order"
    const val NOTIFICATION_TYPE_ABANDONED = "Abandoned"
    const val NOTIFICATION_TYPE_NOTIFICATION_LIST = "Notify List"
    const val USER_FCM_ID = "fcm_id"
    const val STATUS = "status"
    const val SUCCESS = "success"
    const val FAILURE = "failure"
    const val CANCEL = "cancelled"
    const val CANCEL_STATUS = "canceled"
    const val IMAGE_RATIO: Double = 1.40
    const val WIDTH_MARGIN : Int = 40
    const val BANK_RECIPIENT_LABEL: String = "Bank Recipient"
    const val TRANSFER_METHOD_LABEL: String = "Transfer Method"
    const val CART_DE_ACTIVE = "cart de-active"
    const val IS_NOTIFICATION_SHOW = "notification"
    const val IGNORE="ignore"
    const val COUNTRY_CODE_ID = "ID"
    const val COUNTRY_CODE_IN = "in"
    const val COUNTRY_CODE_US = "US"
    const val NOTIFICATION_ID_LIST: String = "USER_NOTIFICATION_IDS"
    val SOFT_INPUT_KEYBOARD_DEF_HEIGHT: Int = 350
    const val PRODUCTION = "production"

    const val ORDER_COMMENT = "[MobileOrder-Android]"

    /*
    * For Facebook event tracker
    */
    const val FB_EVENT_NAME_ADDED_TO_CART = "ADDED TO CART"
    const val FB_EVENT_NAME_ADDED_TO_WISHLIST = "ADDED TO WISHLIST"
    const val FB_EVENT_NAME_PRODUCT_DETAIL = "PRODUCT DETAIL"
    const val FB_EVENT_NAME_INITIATED_CHECKOUT = "INITIATED CHECKOUT"
    const val FB_EVENT_NAME_PURCHASED = "PURCHASED"
    const val FB_EVENT_NAME_SEARCHED = "SEARCHED"
    const val FB_EVENT_BANK_TRANSFER = "BANK TRANSFER"
    const val FB_EVENT_CONTACT_US = "CONTACT US"
    const val FB_EVENT_SUBSCRIBE_TO_NEWSLETTER = "SUBSCRIBE TO NEWSLETTER"
    const val FB_EVENT_BUYING_GUIDE = "BUYING GUIDE"


    const val FB_EVENT_PRODUCT_NAME = "Product Name"
    const val FB_EVENT_PRODUCT_SKU = "Product SKU"
    const val FB_EVENT_QUANTITY = "Quantity"
    const val FB_EVENT_TOTAL_PRICE = "Cart Amount"
    const val FB_EVENT_ORDER_ID = "Order Id"
    const val FB_EVENT_SEARCH_KEYWORD = "Keyword"
    const val FB_EVENT_EMAIL_ID = "Email id"


}